import type {
  User,
  Client,
  Case,
  Lead,
  Task,
  CalendarEvent,
  Document,
  Activity,
  DashboardStats,
  CasesByStatus,
  MonthlyMetrics,
} from '@/types';

// Mock Users (Team Members)
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'ryan.wind@windlaw.com',
    firstName: 'Ryan',
    lastName: 'Wind',
    role: 'admin',
    phone: '(804) 773-3815',
    isActive: true,
    createdAt: new Date('2020-01-01'),
  },
  {
    id: '2',
    email: 'kevin.hadden@windlaw.com',
    firstName: 'Kevin',
    lastName: 'Hadden',
    role: 'attorney',
    phone: '(804) 773-3816',
    isActive: true,
    createdAt: new Date('2021-03-15'),
  },
  {
    id: '3',
    email: 'sarah.mitchell@windlaw.com',
    firstName: 'Sarah',
    lastName: 'Mitchell',
    role: 'paralegal',
    phone: '(804) 773-3817',
    isActive: true,
    createdAt: new Date('2021-06-01'),
  },
  {
    id: '4',
    email: 'marcus.johnson@windlaw.com',
    firstName: 'Marcus',
    lastName: 'Johnson',
    role: 'case_manager',
    phone: '(804) 773-3818',
    isActive: true,
    createdAt: new Date('2022-01-10'),
  },
  {
    id: '5',
    email: 'jennifer.adams@windlaw.com',
    firstName: 'Jennifer',
    lastName: 'Adams',
    role: 'intake_specialist',
    phone: '(804) 773-3819',
    isActive: true,
    createdAt: new Date('2022-08-01'),
  },
];

// Mock Clients
export const mockClients: Client[] = [
  {
    id: 'c1',
    firstName: 'Michael',
    lastName: 'Thompson',
    email: 'michael.thompson@email.com',
    phone: '(804) 555-0123',
    address: {
      street: '123 Main Street',
      city: 'Richmond',
      state: 'VA',
      zipCode: '23220',
    },
    dateOfBirth: new Date('1985-03-15'),
    preferredContactMethod: 'phone',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'c2',
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'sarah.w@email.com',
    phone: '(804) 555-0456',
    address: {
      street: '456 Oak Avenue',
      city: 'Henrico',
      state: 'VA',
      zipCode: '23233',
    },
    dateOfBirth: new Date('1978-07-22'),
    preferredContactMethod: 'email',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'c3',
    firstName: 'James',
    lastName: 'Rodriguez',
    email: 'jrodriguez@email.com',
    phone: '(804) 555-0789',
    address: {
      street: '789 Pine Road',
      city: 'Chester',
      state: 'VA',
      zipCode: '23831',
    },
    dateOfBirth: new Date('1992-11-08'),
    preferredContactMethod: 'text',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'c4',
    firstName: 'Emily',
    lastName: 'Chen',
    email: 'emily.chen@email.com',
    phone: '(804) 555-1234',
    address: {
      street: '321 Maple Drive',
      city: 'Short Pump',
      state: 'VA',
      zipCode: '23233',
    },
    preferredContactMethod: 'email',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'c5',
    firstName: 'Robert',
    lastName: 'Davis',
    email: 'rdavis@email.com',
    phone: '(804) 555-5678',
    address: {
      street: '555 Elm Street',
      city: 'Midlothian',
      state: 'VA',
      zipCode: '23112',
    },
    dateOfBirth: new Date('1965-04-20'),
    preferredContactMethod: 'phone',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-15'),
  },
];

// Mock Cases
export const mockCases: Case[] = [
  {
    id: 'case1',
    caseNumber: 'WL-2024-0012',
    clientId: 'c1',
    client: mockClients[0],
    caseType: 'auto_accident',
    status: 'negotiation',
    priority: 'high',
    title: 'Thompson v. Interstate Trucking Co.',
    description: 'Multi-vehicle collision on I-95 involving commercial truck',
    incidentDate: new Date('2024-01-10'),
    incidentLocation: 'I-95 Southbound, Richmond VA',
    incidentDescription: 'Client was rear-ended by commercial vehicle resulting in serious injuries',
    defendants: [
      {
        id: 'd1',
        name: 'Interstate Trucking Co.',
        type: 'company',
        role: 'defendant',
        attorney: 'Smith & Associates',
      },
    ],
    insuranceCompanies: [
      {
        id: 'ins1',
        name: 'National Commercial Insurance',
        claimNumber: 'NCI-2024-45678',
        adjusterName: 'Patricia Holmes',
        adjusterPhone: '(800) 555-1234',
        policyLimit: 1000000,
        coverageType: 'Commercial Auto',
      },
    ],
    medicalExpenses: 85000,
    lostWages: 45000,
    otherDamages: 25000,
    demandAmount: 450000,
    leadAttorneyId: '1',
    leadAttorney: mockUsers[0],
    assignedStaff: ['3', '4'],
    statuteOfLimitations: new Date('2026-01-10'),
    source: 'referral',
    tags: ['high-value', 'commercial-vehicle', 'serious-injury'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'case2',
    caseNumber: 'WL-2024-0034',
    clientId: 'c2',
    client: mockClients[1],
    caseType: 'slip_and_fall',
    status: 'investigation',
    priority: 'medium',
    title: 'Williams v. Riverside Shopping Center',
    description: 'Slip and fall in parking lot due to icy conditions',
    incidentDate: new Date('2024-01-20'),
    incidentLocation: 'Riverside Shopping Center, Henrico VA',
    incidentDescription: 'Client slipped on untreated ice in shopping center parking lot',
    defendants: [
      {
        id: 'd2',
        name: 'Riverside Shopping Center LLC',
        type: 'company',
        role: 'defendant',
      },
    ],
    insuranceCompanies: [
      {
        id: 'ins2',
        name: 'Commercial Property Insurance Co.',
        claimNumber: 'CPI-2024-12345',
        policyLimit: 500000,
        coverageType: 'General Liability',
      },
    ],
    medicalExpenses: 32000,
    lostWages: 15000,
    otherDamages: 8000,
    leadAttorneyId: '2',
    leadAttorney: mockUsers[1],
    assignedStaff: ['3'],
    statuteOfLimitations: new Date('2026-01-20'),
    source: 'google',
    tags: ['premises-liability', 'weather-related'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: 'case3',
    caseNumber: 'WL-2024-0056',
    clientId: 'c3',
    client: mockClients[2],
    caseType: 'motorcycle_accident',
    status: 'demand',
    priority: 'high',
    title: 'Rodriguez v. Miller',
    description: 'Motorcycle vs car collision at intersection',
    incidentDate: new Date('2024-02-05'),
    incidentLocation: 'Broad St & Boulevard, Richmond VA',
    incidentDescription: 'Client on motorcycle was struck by vehicle running red light',
    defendants: [
      {
        id: 'd3',
        name: 'Thomas Miller',
        type: 'individual',
        role: 'defendant',
      },
    ],
    insuranceCompanies: [
      {
        id: 'ins3',
        name: 'State Auto Insurance',
        claimNumber: 'SAI-2024-78901',
        adjusterName: 'Michael Chen',
        adjusterPhone: '(800) 555-9876',
        policyLimit: 250000,
        coverageType: 'Personal Auto',
      },
    ],
    medicalExpenses: 125000,
    lostWages: 35000,
    otherDamages: 40000,
    demandAmount: 250000,
    leadAttorneyId: '1',
    leadAttorney: mockUsers[0],
    assignedStaff: ['3', '4'],
    statuteOfLimitations: new Date('2026-02-05'),
    source: 'website',
    tags: ['motorcycle', 'red-light', 'serious-injury'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'case4',
    caseNumber: 'WL-2024-0078',
    clientId: 'c4',
    client: mockClients[3],
    caseType: 'workplace_injury',
    status: 'intake',
    priority: 'medium',
    title: 'Chen v. Metro Construction Inc.',
    description: 'Construction site injury - falling debris',
    incidentDate: new Date('2024-11-28'),
    incidentLocation: 'Downtown Richmond Construction Site',
    incidentDescription: 'Client injured by falling construction materials at worksite',
    defendants: [
      {
        id: 'd4',
        name: 'Metro Construction Inc.',
        type: 'company',
        role: 'defendant',
      },
    ],
    insuranceCompanies: [],
    medicalExpenses: 15000,
    lostWages: 8000,
    otherDamages: 0,
    leadAttorneyId: '2',
    leadAttorney: mockUsers[1],
    assignedStaff: ['4'],
    statuteOfLimitations: new Date('2026-11-28'),
    source: 'referral',
    tags: ['workplace', 'construction'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-08'),
  },
  {
    id: 'case5',
    caseNumber: 'WL-2023-0234',
    clientId: 'c5',
    client: mockClients[4],
    caseType: 'auto_accident',
    status: 'settled',
    priority: 'low',
    title: 'Davis v. Johnson',
    description: 'Rear-end collision on Route 1',
    incidentDate: new Date('2023-08-15'),
    incidentLocation: 'Route 1, Chester VA',
    incidentDescription: 'Client rear-ended at traffic light',
    defendants: [
      {
        id: 'd5',
        name: 'Amanda Johnson',
        type: 'individual',
        role: 'defendant',
      },
    ],
    insuranceCompanies: [
      {
        id: 'ins5',
        name: 'GEICO',
        claimNumber: 'G-2023-55555',
        policyLimit: 100000,
        coverageType: 'Personal Auto',
      },
    ],
    medicalExpenses: 28000,
    lostWages: 12000,
    otherDamages: 5000,
    demandAmount: 95000,
    settlementAmount: 85000,
    leadAttorneyId: '1',
    leadAttorney: mockUsers[0],
    assignedStaff: ['3'],
    statuteOfLimitations: new Date('2025-08-15'),
    source: 'google',
    tags: ['settled', 'rear-end'],
    createdAt: new Date('2023-08-20'),
    updatedAt: new Date('2024-11-01'),
  },
];

// Mock Leads
export const mockLeads: Lead[] = [
  {
    id: 'lead1',
    firstName: 'Patricia',
    lastName: 'Martinez',
    email: 'pmartinez@email.com',
    phone: '(804) 555-2222',
    source: 'website',
    status: 'new',
    caseType: 'auto_accident',
    incidentDate: new Date('2024-12-10'),
    incidentDescription: 'T-bone collision at intersection, other driver ran stop sign',
    estimatedValue: 75000,
    assignedTo: '5',
    createdAt: new Date('2024-12-12'),
    updatedAt: new Date('2024-12-12'),
  },
  {
    id: 'lead2',
    firstName: 'David',
    lastName: 'Kim',
    email: 'dkim@email.com',
    phone: '(804) 555-3333',
    source: 'referral',
    status: 'consultation_scheduled',
    caseType: 'nursing_home',
    incidentDescription: 'Mother suffered neglect at assisted living facility',
    estimatedValue: 200000,
    assignedTo: '5',
    followUpDate: new Date('2024-12-18'),
    notes: 'Consultation scheduled for Dec 18 at 2pm',
    createdAt: new Date('2024-12-08'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'lead3',
    firstName: 'Lisa',
    lastName: 'Brown',
    phone: '(804) 555-4444',
    source: 'google',
    status: 'contacted',
    caseType: 'dog_bite',
    incidentDate: new Date('2024-12-05'),
    incidentDescription: 'Bitten by neighbor\'s dog while jogging',
    assignedTo: '5',
    followUpDate: new Date('2024-12-16'),
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-14'),
  },
  {
    id: 'lead4',
    firstName: 'Anthony',
    lastName: 'Garcia',
    email: 'agarcia@email.com',
    phone: '(804) 555-5555',
    source: 'tv_ad',
    status: 'qualified',
    caseType: 'truck_accident',
    incidentDate: new Date('2024-11-28'),
    incidentDescription: 'Collision with 18-wheeler on I-64',
    estimatedValue: 350000,
    assignedTo: '5',
    notes: 'Strong case - clear liability, significant injuries',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-14'),
  },
  {
    id: 'lead5',
    firstName: 'Michelle',
    lastName: 'Taylor',
    phone: '(804) 555-6666',
    source: 'walk_in',
    status: 'not_qualified',
    caseType: 'auto_accident',
    incidentDescription: 'Minor fender bender, no injuries reported',
    notes: 'No medical treatment, property damage only',
    createdAt: new Date('2024-12-13'),
    updatedAt: new Date('2024-12-13'),
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task1',
    caseId: 'case1',
    title: 'Request updated medical records from VCU Health',
    description: 'Need latest treatment records and prognosis',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date('2024-12-18'),
    assignedTo: '3',
    assignee: mockUsers[2],
    createdBy: '1',
    tags: ['medical', 'records'],
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'task2',
    caseId: 'case1',
    title: 'Draft demand letter',
    description: 'Prepare comprehensive demand package for insurance',
    status: 'pending',
    priority: 'high',
    dueDate: new Date('2024-12-22'),
    assignedTo: '1',
    assignee: mockUsers[0],
    createdBy: '1',
    tags: ['demand', 'negotiation'],
    createdAt: new Date('2024-12-12'),
    updatedAt: new Date('2024-12-12'),
  },
  {
    id: 'task3',
    caseId: 'case2',
    title: 'Obtain surveillance footage',
    description: 'Request security camera footage from shopping center',
    status: 'pending',
    priority: 'urgent',
    dueDate: new Date('2024-12-16'),
    assignedTo: '4',
    assignee: mockUsers[3],
    createdBy: '2',
    tags: ['evidence', 'investigation'],
    createdAt: new Date('2024-12-14'),
    updatedAt: new Date('2024-12-14'),
  },
  {
    id: 'task4',
    caseId: 'case3',
    title: 'Schedule IME',
    description: 'Coordinate independent medical examination',
    status: 'completed',
    priority: 'medium',
    dueDate: new Date('2024-12-10'),
    assignedTo: '3',
    assignee: mockUsers[2],
    createdBy: '1',
    completedAt: new Date('2024-12-09'),
    tags: ['medical', 'scheduling'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-09'),
  },
  {
    id: 'task5',
    title: 'Follow up with new leads',
    description: 'Contact all new leads from this week',
    status: 'pending',
    priority: 'medium',
    dueDate: new Date('2024-12-17'),
    assignedTo: '5',
    assignee: mockUsers[4],
    createdBy: '4',
    tags: ['intake', 'leads'],
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'task6',
    caseId: 'case4',
    title: 'Send engagement letter',
    description: 'Prepare and send fee agreement to new client',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date('2024-12-17'),
    assignedTo: '4',
    assignee: mockUsers[3],
    createdBy: '2',
    tags: ['intake', 'contracts'],
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-16'),
  },
];

// Mock Calendar Events
export const mockEvents: CalendarEvent[] = [
  {
    id: 'evt1',
    caseId: 'case1',
    title: 'Mediation - Thompson v. Interstate Trucking',
    description: 'Full day mediation session',
    type: 'mediation',
    startTime: new Date('2024-12-20T09:00:00'),
    endTime: new Date('2024-12-20T17:00:00'),
    location: 'Richmond Mediation Center',
    attendees: ['1', '3'],
    isAllDay: false,
    createdBy: '1',
    createdAt: new Date('2024-12-01'),
  },
  {
    id: 'evt2',
    clientId: 'lead2',
    title: 'Initial Consultation - David Kim',
    description: 'Nursing home neglect case consultation',
    type: 'consultation',
    startTime: new Date('2024-12-18T14:00:00'),
    endTime: new Date('2024-12-18T15:00:00'),
    location: 'Main Office',
    attendees: ['1', '5'],
    isAllDay: false,
    createdBy: '5',
    createdAt: new Date('2024-12-14'),
  },
  {
    id: 'evt3',
    caseId: 'case3',
    title: 'Deposition - Dr. Williams (Expert)',
    type: 'deposition',
    startTime: new Date('2024-12-19T10:00:00'),
    endTime: new Date('2024-12-19T12:00:00'),
    location: 'Court Reporter Office',
    attendees: ['1', '3'],
    isAllDay: false,
    createdBy: '1',
    createdAt: new Date('2024-12-05'),
  },
  {
    id: 'evt4',
    title: 'Statute of Limitations - Rodriguez Case',
    type: 'deadline',
    startTime: new Date('2026-02-05T00:00:00'),
    endTime: new Date('2026-02-05T23:59:59'),
    attendees: ['1'],
    isAllDay: true,
    reminderMinutes: 10080, // 1 week
    createdBy: '1',
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'evt5',
    title: 'Team Meeting',
    description: 'Weekly case review and updates',
    type: 'internal_meeting',
    startTime: new Date('2024-12-17T09:00:00'),
    endTime: new Date('2024-12-17T10:00:00'),
    location: 'Conference Room A',
    attendees: ['1', '2', '3', '4', '5'],
    isAllDay: false,
    recurrence: {
      frequency: 'weekly',
      interval: 1,
    },
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Documents
export const mockDocuments: Document[] = [
  {
    id: 'doc1',
    caseId: 'case1',
    name: 'Police Report - Incident 2024-0110',
    type: 'police_report',
    fileUrl: '/documents/case1/police-report.pdf',
    fileSize: 2450000,
    mimeType: 'application/pdf',
    uploadedBy: '3',
    uploadedAt: new Date('2024-01-20'),
    tags: ['police', 'official'],
  },
  {
    id: 'doc2',
    caseId: 'case1',
    name: 'VCU Health Medical Records',
    type: 'medical_record',
    fileUrl: '/documents/case1/medical-records.pdf',
    fileSize: 8900000,
    mimeType: 'application/pdf',
    uploadedBy: '3',
    uploadedAt: new Date('2024-02-15'),
    tags: ['medical', 'treatment'],
  },
  {
    id: 'doc3',
    caseId: 'case1',
    name: 'Accident Scene Photos',
    type: 'photo_evidence',
    description: 'Photos from accident scene taken by client',
    fileUrl: '/documents/case1/scene-photos.zip',
    fileSize: 45000000,
    mimeType: 'application/zip',
    uploadedBy: '4',
    uploadedAt: new Date('2024-01-18'),
    tags: ['evidence', 'photos'],
  },
  {
    id: 'doc4',
    caseId: 'case2',
    name: 'Incident Report - Riverside Shopping',
    type: 'other',
    fileUrl: '/documents/case2/incident-report.pdf',
    fileSize: 1200000,
    mimeType: 'application/pdf',
    uploadedBy: '3',
    uploadedAt: new Date('2024-02-05'),
    tags: ['incident', 'property'],
  },
  {
    id: 'doc5',
    caseId: 'case3',
    name: 'Insurance Policy Declaration',
    type: 'insurance_document',
    fileUrl: '/documents/case3/policy-dec.pdf',
    fileSize: 890000,
    mimeType: 'application/pdf',
    uploadedBy: '4',
    uploadedAt: new Date('2024-02-20'),
    tags: ['insurance', 'policy'],
  },
];

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: 'act1',
    type: 'document_uploaded',
    caseId: 'case1',
    userId: '3',
    user: mockUsers[2],
    description: 'uploaded updated medical records',
    createdAt: new Date('2024-12-15T14:30:00'),
  },
  {
    id: 'act2',
    type: 'case_updated',
    caseId: 'case3',
    userId: '1',
    user: mockUsers[0],
    description: 'moved case to Demand status',
    createdAt: new Date('2024-12-15T11:15:00'),
  },
  {
    id: 'act3',
    type: 'task_completed',
    caseId: 'case3',
    userId: '3',
    user: mockUsers[2],
    description: 'completed task: Schedule IME',
    createdAt: new Date('2024-12-14T16:45:00'),
  },
  {
    id: 'act4',
    type: 'case_created',
    caseId: 'case4',
    clientId: 'c4',
    userId: '2',
    user: mockUsers[1],
    description: 'created new case: Chen v. Metro Construction',
    createdAt: new Date('2024-12-14T10:00:00'),
  },
  {
    id: 'act5',
    type: 'note_added',
    caseId: 'case1',
    userId: '4',
    user: mockUsers[3],
    description: 'added note regarding settlement discussions',
    createdAt: new Date('2024-12-13T15:20:00'),
  },
  {
    id: 'act6',
    type: 'deadline_approaching',
    caseId: 'case2',
    userId: '1',
    user: mockUsers[0],
    description: 'Surveillance footage deadline in 2 days',
    createdAt: new Date('2024-12-14T09:00:00'),
  },
];

// Dashboard Statistics
export const mockDashboardStats: DashboardStats = {
  activeCases: 4,
  newLeadsThisMonth: 12,
  pendingTasks: 8,
  upcomingDeadlines: 3,
  totalRecovered: 4250000,
  avgCaseValue: 156000,
  conversionRate: 68,
  casesWonThisYear: 28,
};

// Cases by Status for charts
export const mockCasesByStatus: CasesByStatus[] = [
  { status: 'intake', count: 3, totalValue: 125000 },
  { status: 'investigation', count: 5, totalValue: 450000 },
  { status: 'demand', count: 4, totalValue: 680000 },
  { status: 'negotiation', count: 6, totalValue: 1250000 },
  { status: 'litigation', count: 2, totalValue: 890000 },
  { status: 'settled', count: 12, totalValue: 2800000 },
];

// Monthly Metrics for charts
export const mockMonthlyMetrics: MonthlyMetrics[] = [
  { month: 'Jan', newCases: 8, closedCases: 5, revenue: 285000, leads: 24 },
  { month: 'Feb', newCases: 6, closedCases: 7, revenue: 420000, leads: 18 },
  { month: 'Mar', newCases: 10, closedCases: 4, revenue: 195000, leads: 32 },
  { month: 'Apr', newCases: 7, closedCases: 6, revenue: 380000, leads: 21 },
  { month: 'May', newCases: 9, closedCases: 8, revenue: 520000, leads: 28 },
  { month: 'Jun', newCases: 11, closedCases: 5, revenue: 310000, leads: 35 },
  { month: 'Jul', newCases: 8, closedCases: 9, revenue: 680000, leads: 22 },
  { month: 'Aug', newCases: 6, closedCases: 7, revenue: 445000, leads: 19 },
  { month: 'Sep', newCases: 12, closedCases: 6, revenue: 290000, leads: 38 },
  { month: 'Oct', newCases: 9, closedCases: 10, revenue: 725000, leads: 27 },
  { month: 'Nov', newCases: 7, closedCases: 8, revenue: 580000, leads: 23 },
  { month: 'Dec', newCases: 5, closedCases: 3, revenue: 185000, leads: 15 },
];
